./aligned_reid/model/Model.py:20: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.fc.weight, std=0.001)
./aligned_reid/model/Model.py:21: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(self.fc.bias, 0)
Traceback (most recent call last):
  File "script/experiment/train.py", line 637, in <module>
    main()
  File "script/experiment/train.py", line 394, in main
    test(load_model_weight=True)
  File "script/experiment/train.py", line 384, in test
    inp.eval(normalize_feat=cfg.normalize_feature, use_local_distance=use_local_distance)
  File "/home/developer/Desktop/reid/AlignedReID-Re-Production-Pytorch-master/script/experiment/extract_feat_image.py", line 58, in eval
    global_feats, local_feats = self.extract_feat(normalize_feat)
  File "/home/developer/Desktop/reid/AlignedReID-Re-Production-Pytorch-master/script/experiment/extract_feat_image.py", line 147, in extract_feat
    ims_names,ims_,done= self.getstackedimages()
  File "/home/developer/Desktop/reid/AlignedReID-Re-Production-Pytorch-master/script/experiment/extract_feat_image.py", line 40, in getstackedimages
    im1 = img.imread(im_path)
  File "/opt/miniconda3/envs/pytorch_env/lib/python2.7/site-packages/matplotlib/image.py", line 1356, in imread
    im = pilread(fname)
  File "/opt/miniconda3/envs/pytorch_env/lib/python2.7/site-packages/matplotlib/image.py", line 1334, in pilread
    with Image.open(fname) as image:
  File "/opt/miniconda3/envs/pytorch_env/lib/python2.7/site-packages/PIL/Image.py", line 2609, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 21] Is a directory: '/home/developer/test_images/2'
